version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite://./local.db}
    volumes:
      - ./local.db:/app/local.db
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=performance_metrics
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

